export const Categories = [
  {
    id: 1,
    title: "Milks and Dairies",
    imageUrl: "/images/cat7.png",
    items: 24,
    bg: "#FFFCEB",
  },
  {
    id: 2,
    title: "Clothing & beauty",
    imageUrl: "/images/cat2.png",
    items: 25,
    bg: "#ecffec",
  },
  {
    id: 3,
    title: "Pet Foods & Toy",
    imageUrl: "/images/cat3.png",
    items: 26,
    bg: "#feefea",
  },
  {
    id: 4,
    title: "Milks and Dairies",
    imageUrl: "/images/cat4.png",
    items: 27,
    bg: "#feefea",
  },
  {
    id: 5,
    title: "Milks and Dairies",
    imageUrl: "/images/cat5.png",
    items: 28,
    bg: "#fff3ff",
  },
  {
    id: 6,
    title: "Milks and Dairies",
    imageUrl: "/images/cat6.png",
    items: 29,
    bg: "#f2fce4",
  },
  {
    id: 7,
    title: "Red Apple",
    imageUrl: "/images/cat6.png",
    items: 30,
    bg: "#f2fce4",
  },
  {
    id: 8,
    title: "Red Apple",
    imageUrl: "/images/cat6.png",
    items: 30,
    bg: "#f2fce4",
  },
];

/**Products */

export const Products = [
  {
    id: 1,
    title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    imageUrl: "images/products/beautycare.png",
    category: "smartphone",
    rating: 4,
    price: 1500,
    discount: 3000,
    tag: "hot",
    brand: "samsung",
  },
  {
    id: 2,
    title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    imageUrl: "images/products/scanner.png",
    category: "smartphone",
    rating: 4,
    price: 1500,
    discount: 3000,
    tag: "hot",
    brand: "samsung",
  },
  {
    id: 3,
    title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    imageUrl: "images/products/catshoes.png",
    category: "smartphone",
    rating: 4,
    price: 1500,
    discount: 3000,
    tag: "hot",
    brand: "samsung",
  },
  {
    id: 4,
    title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    imageUrl: "images/products/imac.png",
    category: "smartphone",
    rating: 3.5,
    price: 1500,
    discount: 3000,
    tag: "hot",
    brand: "samsung",
  },
  {
    id: 5,
    title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    imageUrl: "images/products/led.png",
    category: "smartphone",
    rating: 5,
    price: 1500,
    discount: 3000,
    tag: "hot",
    brand: "samsung",
  },
  {
    id: 6,
    title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    imageUrl: "images/products/bluewatch.png",
    category: "smartphone",
    rating: 4,
    price: 1500,
    discount: 3000,
    tag: "hot",
    brand: "samsung",
  },
  {
    id: 7,
    title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    imageUrl: "images/products/graywathch.png",
    category: "smartphone",
    rating: 4,
    price: 1500,
    discount: 3000,
    tag: "hot",
    brand: "samsung",
  },
  {
    id: 8,
    title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    imageUrl: "images/products/headphone.png",
    category: "smartphone",
    rating: 4,
    price: 1500,
    discount: 3000,
    tag: "hot",
    brand: "samsung",
  },
  {
    id: 9,
    title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    imageUrl: "images/products/androidphone.png",
    category: "smartphone",
    rating: 4,
    price: 1500,
    discount: 3000,
    tag: "hot",
    brand: "samsung",
  },
  {
    id: 10,
    title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    imageUrl: "images/products/iphone.png",
    category: "smartphone",
    rating: 4,
    price: 1500,
    discount: 3000,
    tag: "hot",
    brand: "samsung",
  },
]
