export const Categories = [
  {
    id: 1,
    title: "Milks and Dairies",
    imageUrl: "/images/cat7.png",
    items: 24,
    bg: "#FFFCEB",
  },
  {
    id: 2,
    title: "Clothing & beauty",
    imageUrl: "/images/cat2.png",
    items: 25,
    bg: "#ecffec",
  },
  {
    id: 3,
    title: "Pet Foods & Toy",
    imageUrl: "/images/cat3.png",
    items: 26,
    bg: "#feefea",
  },
  {
    id: 4,
    title: "Milks and Dairies",
    imageUrl: "/images/cat4.png",
    items: 27,
    bg: "#feefea",
  },
  {
    id: 5,
    title: "Milks and Dairies",
    imageUrl: "/images/cat5.png",
    items: 28,
    bg: "#fff3ff",
  },
  {
    id: 6,
    title: "Milks and Dairies",
    imageUrl: "/images/cat6.png",
    items: 29,
    bg: "#f2fce4",
  },
  {
    id: 7,
    title: "Red Apple",
    imageUrl: "/images/cat6.png",
    items: 30,
    bg: "#f2fce4",
  },
  {
    id: 8,
    title: "Red Apple",
    imageUrl: "/images/cat6.png",
    items: 30,
    bg: "#f2fce4",
  },
];

/**Products */

export const Products = [
  {
    id: 1,
    title: "Himalaya Softness & Shine Daily Care 2-In-1 Shampoo Conditions Hair, Making It Smooth & Shiny -400 ml",
    imageUrl: "images/products/beautycare.png",
    category: "beauty",
    rating: 4,
    price: 1200,
    discount: 500,
    tag: "hoy",
    bg: "",
    brand: "himalaya",
    featured: true,
    views: 20,
  },
  {
    id: 2,
    title: "Handheld Barcode Scanner 1D/2D/QR Code Scanner 2.4G Wireless & USB Wired Bar Code Compatible with Windows Mac Linux for Supermarket Retail Library Logistics Warehous",
    imageUrl: "images/products/scanner.png",
    category: "accessories",
    rating: 4,
    price: 12000,
    discount: 11000,
    tag: "new",
    bg: "",
    brand: "sony",
    featured: true,
    views: 21,
  },
  {
    id: 3,
    title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    imageUrl: "images/products/catshoes.png",
    category: "smartphone",
    rating: 4,
    price: 1500,
    discount: 3000,
    tag: "hot",
    brand: "samsung",
    featured: false,
    views: 22,
  },
  {
    id: 4,
    title: "Apple MacBook Pro 16 M1 Retina XDR Laptop",
    imageUrl: "images/products/imac.png",
    category: "computer",
    rating: 3.5,
    price: 1690000,
    discount: 1390000,
    tag: "new",
    bg: "",
    brand: "apple",
    featured: false,
    views: 23,
  },
  {
    id: 5,
    title: "50 Inch 4K UHD Smart LED TV, HDR Crystal Processor 4K With Tizen OS, 60 Hz Refresh rates and Built-In Receiver Model (2021). UA50AU7000UXUM Black",
    imageUrl: "images/products/led.png",
    category: "led",
    rating: 5,
    price: 350000,
    discount: 180000,
    tag: "trendy",
    bg: "",
    brand: "samsung",
    featured: false,
    views: 24,
  },
  {
    id: 6,
    title: "Huawei Watch Gt 2 Pro Smartwatch, 1.39 Amoled Hd Touchscreen, 2-Week Battery Life, Gps And Glonass,100 Plus Workout Modes, Bluetooth Calling, Heartrate Monitoring, Gray Brown Nebula, Gray GT 46mm",
    imageUrl: "images/products/bluewatch.png",
    category: "smartwatch",
    rating: 4,
    price: 73900,
    discount: 73900,
    tag: "trendy",
    bg: "",
    brand: "huawei",
    featured: true,
    views: 25,
  },
  {
    id: 7,
    title: "SoundPEATS Watch 2 Smartwatch SpO2 with 12 Sports Modes Fitness Tracker Heart Rate Sleep Quality Monitor IP68 Waterproof Smart Watches Compatible with iPhone Android Phones, Smart watch for Men Women",
    imageUrl: "images/products/graywathch.png",
    category: "smartwatch",
    rating: 4,
    price: 14900,
    discount: 11100,
    tag: "new",
    bg: "",
    brand: "SoundPEATS",
    featured: true,
    views: 25,
  },
  {
    id: 8,
    title: "Lenovo HD200 Bluetooth Headphone with Microphone - Black",
    imageUrl: "images/products/headphone.png",
    category: "headphone",
    rating: 4,
    price: 8500,
    discount: 8000,
    tag: "new",
    bg: "",
    brand: "lenovo",
    featured: true,
    views: 26,

  },
  {
    id: 9,
    title: "SAMSUNG Galaxy A73 5G Android Smartphone, 256 GB, 8 GB RAM, Dual Sim Mobile Phone, Awesome Mint (UAE Version)",
    imageUrl: "images/products/androidphone.png",
    category: "smartphone",
    rating: 4,
    price: 176800,
    discount: 150000,
    tag: "new",
    bg: "",
    brand: "samsung",
    featured: false,
    views: 27,


  },
  {
    id: 10,
    title: "New Apple iPhone 14 Pro (512 GB) - Gold",
    imageUrl: "images/products/iphone.png",
    category: "smartphone",
    rating: 4,
    price: 6000,
    discount: 5500,
    tag: "hot",
    bg: "",
    brand: "apple",
    featured: false,
    views: 27,
  },
]
